[project]
name = "prueba-tecnica-imagine-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anthony Martínez", email = "anthony.mart996@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
prueba-tecnica-imagine-apps = "prueba_tecnica_imagine_apps:main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "apps/api",
]
